#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

import os

AUTHOR = u'Rahul Agarwal'

SITENAME = u'mlwhiz'
SITESUBTITLE = u'Turning data into insights'
# Change in publishconf.py and ignore the WARNING.  This is needed so you
# can inspect the site using a web-server at locahost.
SITEURL = 'http://mlwhiz.github.io'
RELATIVE_URLS = False
# Times and dates.
DEFAULT_DATE_FORMAT = '%b %d, %Y'
TIMEZONE = 'America/Sao_Paulo'
DEFAULT_LANG = u'en'

# Set the article URL.
ARTICLE_URL = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/'
ARTICLE_SAVE_AS = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/index.html'

# Title menu options.
uri = 'http://mlwhiz.com'
MENUITEMS = [('Blog', '%s' % uri),
             ('Archives', '%s/archives.html' % uri),
             ('About', '%s/pages/about.html' % uri),
             ('Great Links', '%s/pages/links.html' % uri),
             ]
NEWEST_FIRST_ARCHIVES = True

# Github include settings.
#GITHUB_USER = 'ocefpaf'
#GITHUB_REPO_COUNT = 0
#GITHUB_SKIP_FORK = True
#GITHUB_SHOW_USER_LINK = True

# Blogroll.
'''
LINKS =  (('PyAOS', 'http://pyaos.johnny-lin.com/'),
          ('EarthPy', 'http://earthpy.org/'),
          ("Rich Signell's Notebook Blog",
              'http://rsignell-usgs.github.io/blog/'),
          ('drclimate', 'http://drclimate.wordpress.com/'),
          ('Software Carpentry',
           'http://software-carpentry.org/blog/index.html'),)
'''
# Social widget.
SOCIAL = (('twitter', 'http://twitter.com/mlwhiz'),
          )

DEFAULT_PAGINATION = 10

# STATIC_OUT_DIR requires pelican 3.3+.
STATIC_PATHS = ['images', 'figures', 'downloads', 'favicon.png']
CODE_DIR = 'downloads/code'
NOTEBOOK_DIR = 'downloads/notebooks'

# Theme and plug-ins.
THEME = '../pelican-octopress-theme'
PLUGIN_PATH = '../pelican-plugins'
PLUGINS = ['render_math','summary','sitemap','liquid_tags.img', 'liquid_tags.video','liquid_tags.include_code','liquid_tags.notebook','liquid_tags.literal']

SITEMAP = {'format': 'xml', 'priorities': {'articles': 0.5,'indexes': 0.5,'pages': 0.5},'changefreqs': {'articles': 'monthly','indexes': 'daily','pages': 'monthly'}}

DISPLAY_PAGES_ON_MENU = False
DISPLAY_CATEGORIES_ON_MENU = False

# The theme file should be updated so that the base header contains the line:
# {% if EXTRA_HEADER %}
# {{ EXTRA_HEADER }}
# {% endif %}

# This header file is automatically generated by the notebook plugin.
if not os.path.exists('_nb_header.html'):
    import warnings
    warnings.warn("_nb_header.html not found.  "
                  "Rerun make html to finalize build.")
else:
    EXTRA_HEADER = open('_nb_header.html').read().decode('utf-8')

# Sharing
TWITTER_USER = 'MLWhiz'
GOOGLE_PLUS_USER = '100605939802712127513'
GOOGLE_PLUS_ONE = True
GOOGLE_PLUS_HIDDEN = False
FACEBOOK_LIKE = True
TWITTER_TWEET_BUTTON = True
TWITTER_LATEST_TWEETS = True
TWITTER_FOLLOW_BUTTON = True
TWITTER_TWEET_COUNT = 3
TWITTER_SHOW_REPLIES = 'false'
TWITTER_SHOW_FOLLOWER_COUNT = 'true'

# RSS/Atom feeds
FEED_DOMAIN = 'http://mlwhiz.github.io'
FEED_ATOM = 'atom.xml'
FEED_RSS = "feed.rss"
RSS_FEED_SUMMARY_ONLY = True
FEED_MAX_ITEMS = 10
# Search
SEARCH_BOX = True


GOOGLE_ANALYTICS='UA-54777926-1'
DISQUS_SITENAME='mlwhiz'
DISQUS_SECRET_KEY = u'i1sT7tWFeEY2E2CKpPtLK6L8ZWZwvGkKKfNQR5wp7z8K0KOef0o0uq0BvSm3lhtu'
